package org.example;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
public class Servlet_pra extends HttpServlet {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)throws IOException{
        response.getWriter().println("高橋尚輝　is ヤクザ★");//レスポンスに出力するメッセージを設定
    }
}
//jspで実行する際、
// Tomcat deploy C:\Users\Nishineko\Desktop\Java\Servlet\src\webapp
// port 8080
//deployのファイル内に設置している奴今回だとwebapp内のディレクトリにファイルおかないと反映されない



/*
<!--
<%@ page contentType="text/html; charset=UTF-8" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Dynamic Content Example</title>
    <style>
        .red {
            color: red;
        }
    </style>
    <script>
        function greet() {
            var name = document.getElementById("name").value;
            var greeting = "Hello, " + name + "!";
            document.getElementById("output").innerText = greeting;
        }
    </script>
</head>
<body>
    <h1>Dynamic Content Example</h1>
    <form>
        Enter your name: <input type="text" id="name">
        <button type="button" onclick="greet()">Greet</button>
    </form>
    <div id="output" class="red"></div>

    <% String message = "This message is generated by Java code in JSP.";
        out.println("<p>" + message + "</p>"); %>
</body>
</html>
-->
 */